file(DOWNLOAD "https://raw.githubusercontent.com/flagarde/CMakeCM/main/modules/Pong.cmake" "${CMAKE_CURRENT_BINARY_DIR}/Pong.cmake" STATUS PING_STATUS TIMEOUT 3)
list(GET PING_STATUS 0 PING_RC)
list(GET PING_STATUS 1 PING_MSG)
if(${PING_RC})
  set(IS_ONLINE FALSE)
  set(IS_OFFLINE TRUE)
else()
  include(${CMAKE_CURRENT_BINARY_DIR}/Pong.cmake)
  if(${PING_RESPONSE} STREQUAL "Pong")
    set(IS_ONLINE TRUE)
    set(IS_OFFLINE FALSE)
  else()
    set(IS_ONLINE FALSE)
    set(IS_OFFLINE TRUE)
  endif()
  unset(PING_RESPONSE)
endif()
