file(DOWNLOAD "https://cdn.jsdelivr.net/gh/flagarde/Ping/Ping.cmake" "${CMAKE_CURRENT_BINARY_DIR}/Ping.cmake" STATUS PING_STATUS TIMEOUT 3)
list(GET PING_STATUS 0 PING_RC)
list(GET PING_STATUS 1 PING_MSG)
if(${PING_RC})
  set(IS_ONLINE FALSE)
  set(IS_OFFLINE TRUE)
else()
  include(${CMAKE_CURRENT_BINARY_DIR}/Ping.cmake)
  if(${PING_RESPONSE} STREQUAL "Pong")
    set(IS_ONLINE TRUE)
    set(IS_OFFLINE FALSE)
  else()
    set(IS_ONLINE FALSE)
    set(IS_OFFLINE TRUE)
  endif()
  unset(PING_RESPONSE)
endif()

file(DOWNLOAD "https://raw.githubusercontent.com/flagarde/Ping/master/Ping.cmake" "${CMAKE_CURRENT_BINARY_DIR}/Ping.cmake" STATUS PING_STATUS TIMEOUT 3)
list(GET PING_STATUS 0 PING_RC)
list(GET PING_STATUS 1 PING_MSG)
if(${PING_RC})
  set(IS_ONLINE_RAW FALSE)
  set(IS_OFFLINE_RAW TRUE)
else()
  include(${CMAKE_CURRENT_BINARY_DIR}/Ping.cmake)
  if(${PING_RESPONSE} STREQUAL "Pong")
    set(IS_ONLINE_RAW TRUE)
    set(IS_OFFLINE_RAW FALSE)
  else()
    set(IS_ONLINE_RAW FALSE)
    set(IS_OFFLINE_RAW TRUE)
  endif()
  unset(PING_RESPONSE)
endif()
