cmcm_module(Colors.cmake LOCAL modules/Colors.cmake VERSION 1)
cmcm_module(CPM.cmake LOCAL modules/CPM.cmake VERSION 1)
cmcm_module(DefaultInstallPrefix.cmake LOCAL modules/DefaultInstallPrefix.cmake VERSION 1)
cmcm_module(Messages.cmake LOCAL modules/Messages.cmake VERSION 1)
cmcm_module(Ping.cmake LOCAL modules/Ping.cmake VERSION 1)
cmcm_module(PreventInSourceBuilds.cmake LOCAL modules/PreventInSourceBuilds.cmake VERSION 1)
cmcm_module(Standards.cmake LOCAL modules/Standards.cmake VERSION 1)
cmcm_module(Testings.cmake LOCAL modules/Testings.cmake VERSION 1)
