name: 'MacOS Clang'

env:
  CMAKE_VERSION: '3.16.x'
  CMAKE_BUILD_TYPE: 'Release'
  CMAKE_BUILD_PREFIX: './build'

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        cmake-version: ['3.16','3.17','3.18','3.19','3.20','3.21']
    name: '🧪🟨 Test CMake ${{ matrix.cmake-version }} Clang'

    steps:
    - name: '🧰 Checkout'
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - name: '${{ matrix.icon }} Setup CMake'
      uses: jwlawson/actions-setup-cmake@v1.11
      with:
        cmake-version: '${{ matrix.cmake-version }}.x'
        github-api-token: ${{ secrets.GITHUB_TOKEN }}

    - name: '🧪 Run tests'
      env:
        CC: ${{matrix.cc}}
        CXX: ${{matrix.cxx}}
      run: cmake -DBUILD_TESTS=ON -S . -B build
