name: 'Windows MSVC'

env:
  CMAKE_BUILD_TYPE: 'Release'
  CMAKE_BUILD_PREFIX: './build'
  CMAKE_SOURCE_PREFIX: '.'
  BUILD_TESTS: YES
  BUILD_DOCS: NO
  BUILD_EXAMPLES: NO

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        cmake-version: ['3.16','3.17','3.18','3.19','3.20','3.21']
    name: '🟨🧪 Test CMake ${{ matrix.cmake-version }} MSVC'

    steps:
    - name: '🧰 Checkout'
      uses: actions/checkout@v2.3.5
      with:
        fetch-depth: 0

    - name: '🟨 Setup CMake'
      uses: jwlawson/actions-setup-cmake@v1.11
      with:
        cmake-version: '${{ matrix.cmake-version }}.x'
        github-api-token: ${{ secrets.GITHUB_TOKEN }}

    - name: '🟨 Setup Visual Studio'
      uses: ilammy/msvc-dev-cmd@v1.10.0

    - name: '🔧 Configure'
      run: cmake -S ${{ env.CMAKE_SOURCE_PREFIX }} -B ${{ env.CMAKE_BUILD_PREFIX }} -D CMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} -D BUILD_TESTS=${{ env.BUILD_TESTS }} -D BUILD_DOCS=${{ env.BUILD_DOCS }} -D BUILD_EXAMPLES=${{ env.BUILD_EXAMPLES }} -Thost=x64

    - name: '🧪 Run tests'
      working-directory: ${{ env.CMAKE_BUILD_PREFIX }}
      run: ctest -C ${{ env.CMAKE_BUILD_TYPE }} -VV --output-on-failure
